name: Release
run-name: ${{ format('{0} {1}', inputs.is-dry-run && 'Dry-run' || 'Release', inputs.tag) }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag / Version number"
        required: true
      is-dry-run:
        description: "Dry-run (do not publish, only test build)"
        type: boolean
        default: true

permissions:
  contents: write

env:
  changelog: CHANGELOG.md
  thunderstoreconfig: thunderstore.toml
  build-dir: build
  artifact-content-type: application/zip
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  release:
    name: ${{ format('{0} {1}', inputs.is-dry-run && 'Dry-run' || 'Release', inputs.tag) }}
    runs-on: windows-latest
    steps:
      - name: Check input tag format
        shell: pwsh
        run: |
          if (-not ("${{ inputs.tag }}" -match '^[0-9]+\.[0-9]+\.[0-9]+$')) {
            Write-Error "Invalid version. Must follow Major.Minor.Patch (e.g. 1.45.320)"
            exit 1
          }

      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: true

      - name: Rotate unreleased section in changelog
        uses: thomaseizinger/keep-a-changelog-new-release@77ac767b2f7f6edf2ee72ab3364ed26667086f96
        with:
          tag: ${{ inputs.tag }}

      - name: Rotate version in Thunderstore CLI config
        shell: pwsh
        run: |
          (Get-Content $env:thunderstoreconfig -Raw) -replace 'versionNumber = ".*?"', "versionNumber = `"${{ inputs.tag }}`"" | Set-Content $env:thunderstoreconfig -NoNewline
          (Get-Content README.md) -replace 'images/', 'https://media.githubusercontent.com/media/adi1998/MelSkin/refs/heads/main/images/' |
            Set-Content README.md

      - name: Install Thunderstore CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          gh release download 0.3.3-hades2 --repo adi1998/thunderstore-cli --pattern "*win-x64.zip"
          Expand-Archive tcli-0.3.3-hades2-win-x64.zip -DestinationPath ./
          echo "$PWD/tcli-0.3.3-hades2-win-x64" >> "$env:GITHUB_PATH"

      - name: Install pip packages
        shell: pwsh
        run: pip install pillow lz4 etcpak deppth2 PyTexturePacker

      - name: Add .NET tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Build package
        shell: pwsh
        run: |
          .\build.ps1
          $artifact = Get-ChildItem "${{ env.build-dir }}" -File | Select-Object -ExpandProperty Name
          echo "artifact-name=$artifact" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "artifact-path=${{ env.build-dir }}/$artifact" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload artifact to workflow
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.artifact-path }}
          retention-days: 1

      - name: Publish package
        if: ${{ !inputs.is-dry-run }}
        shell: pwsh
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
        run: tcli publish --file ${{ env.artifact-path }}

      - name: Tag and push to repository
        if: ${{ !inputs.is-dry-run }}
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add $env:changelog $env:thunderstoreconfig
          git commit -m "Release ${{ inputs.tag }}"
          git tag ${{ inputs.tag }} -a -m "Release ${{ inputs.tag }}"
          git push origin HEAD:${{ github.ref_name }} --tags

      - name: Create release and upload artifact
        if: ${{ !inputs.is-dry-run }}
        run: |
          gh release create \
            '${{ inputs.tag }}' \
            '${{ env.artifact-path }}' \
            --title '${{ inputs.tag }}' \
            --repo '${{ github.repository }}' \
            --target '${{ github.ref_name }}' \
            --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
